# fly.toml app configuration file generated for aquathallyon on 2026-02-10T00:05:59+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'aquathallyon'
primary_region = 'sin'

[build]


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
